spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/emsdb
    username: EMS
    password: bonnie&clyde
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

admin:
  email: bilalidris011@gmail.com
  password: bonnie&clyde
  fullName: bilal idris
  phoneNumber: "08146831917"